stripeKey = "sk_stripesecretkey"
stripePublicKey = "pk_stripepublickey"
itemName = "Donation"
baseURL = "https://donate.example.org"
name = "My fantastic organization"
disclaimer = "All donations are tax deductable, as \"My fantastic organization\" maintains a 501(c)(3) status with the IRS."
successMessage = "Thank you for your donation. You will receive an email recipt which can be used for tax deduction purposes."
failureMessage = "You can try again later."
stopRecurInstructions = "To cancel your recurring donation, email hello@example.org"