# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Donorfide
email: hey@donorfide.org
description: >- # this means to ignore newlines until "baseurl:"
  Donorfide is an open-source, online payment processing and donor management platform
  that allows your nonprofit to process donations easily, so you can focus on doing good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  style: compressed

highlighter: rouge

version: v3.0.0-alpha.1
prerelease: true
demo: https://demo.donorfide.org

banner:
  show: true
  type: info
  message: >-
    This is the documentation for Donorfide 3.0, which is in alpha.
    The latest stable version is **EasyDonate 2.0**, which can be found on the `master` branch of
    this repository, or on GitHub [here](https://github.com/willbarkoff/donorfide/tree/master).
